Repository breadtubetv/bake, pull requests merged in 2019-04, with the labels that each got.

#5 Update documentation, import paths and fixed spelling of videos.go
  CONTRIBUTING.md
  LICENSE
  README.md
  cmd/import.go
  cmd/root.go
  cmd/update.go
  main.go
  providers/youtube.go
  providers/youtube_test.go
  util/videos.go
Labels: bugfix

#8 Download YouTube Description
  cmd/update.go
  providers/youtube.go
Labels: content/channels, needs review

#11 Content Page Type 'Channel'
  util/channel.go
Labels: needs review

#12 Create Video Dir
  providers/youtube.go
  util/videos.go
Labels: content/channels, content/video, needs review, xp/developer
