Repository breadtubetv/bake, pull requests merged in 2019-05, with the labels that each got.

#13 Add CircleCI Config
  .circleci/config.yml
  go.mod
  go.sum
Labels: needs review

#16 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: needs review

#14 Add API key option for use in CI
  .circleci/config.yml
  providers/youtube.go
Labels: needs review

#19 Import using video URL
  cmd/video.go
Labels: enhancement, needs review, xp/developer

#20 Linting, Pre-Commit, and Release
  .circleci/config.yml
  .errcheck-exclude
  .golangci.dev.yml
  .golangci.yml
  .goreleaser.yml
  .pre-commit-config.yaml
  README.md
  cmd/root.go
  cmd/update.go
  go.mod
  go.sum
  main.go
  providers/youtube.go
  util/channel.go
  version.go
Labels: maintenance, needs review, xp/developer

#23 Add Video to top
  util/channel.go
Labels: needs review

#24 fix env var for go-mod-tidy
  .pre-commit-config.yaml
Labels: bugfix, needs review

#25 Support for Channel Folder and Tags
  util/channel.go
Labels: content/channels, needs review, xp/developer
